### ISSUE TITLE
Honey slime hitbox.

### ISSUE THREAD

**Issue by DigitalWendigo** [rikka0w0/MobZReborn#14]
The hitboxes of honey slimes are all over the place, making them pretty much impossible to hit with anything other than a sword that has sweeping edge, and you need to hit something else while nxt to it to work. Otherwise you can just spam click all over the area around the slime and not hit anything.

**Comment by rikka0w0** [comment]
This test build corrects this problem:
https://github.com/rikka0w0/MobZReborn/issues/12#issuecomment-1114050246

Can you try it and give me some feedback?
