### ISSUE TITLE
Fiora bug...?

### ISSUE THREAD

**Issue by DigitalWendigo** [rikka0w0/MobZReborn#15]
I'm not sure if it's even a bug, but I can't seem to make this entity work?
Gave it gold nuggets, gave it food which apparently you can do.
But it just stands there and does.. Nothing. 
Doesn't follow you, doesn't defend you, nothing. 
Just stays put in one spot no matter what.
Is there something special about this mob that needs to be done?
I even got the advancement to trigger for 'best friends forever', so the gold nuggets seemingly worked?
Does the mob do anything else aside just existing?
Does it need to be given commands?

**Comment by BenjaminWallace** [comment]
To add on since I just ran into this same conundrum: 
Hitting Fiora once seemed to allow it to follow me, however I seem to be unable to heal it with food and/or gold nuggets, the latter of which seems to be the intended healing method by a quick glance the source code.

**Comment by rikka0w0** [comment]
Looking at https://github.com/rikka0w0/MobZReborn/blob/f725f16fa776030ca24455d060d62fe7dc441d8d/src/main/java/net/mobz/entity/Knight4Entity.java#L150

and 

https://github.com/rikka0w0/MobZReborn/blob/f725f16fa776030ca24455d060d62fe7dc441d8d/src/main/java/net/mobz/entity/Knight4Entity.java#L215

there seems to be an inconsistency of taming item, could be left-over bugs from the original mobz

**Comment by rikka0w0** [comment]
Fixed, check out this:
https://github.com/rikka0w0/MobZReborn/releases/tag/3.3.4_1.18.2
