### ISSUE TITLE
Mod Loading Error

### ISSUE THREAD

**Issue by Dustalis** [rikka0w0/MobZReborn#19]
Crashed while loading due to Mobz.
Load sucessful without Mobz.
Pastebin of crash report: https://pastebin.com/QH5GtZTi
Minecraft Version: 1.18.2
Mobz Version: 3.3.0

**Comment by rikka0w0** [comment]
Try this and give some feedback pls

https://github.com/rikka0w0/MobZReborn/releases/tag/3.3.3_1.18.2
