### ISSUE TITLE
Another Crash on my Modpackserver

### ISSUE THREAD

**Issue by TheButterbrotMan** [rikka0w0/MobZReborn#20]
https://bytebin.lucko.me/oOLd2YvW2w

**Comment by TheButterbrotMan** [comment]
https://github.com/rikka0w0/MobZReborn/issues/17

**Comment by rikka0w0** [comment]
Try this and give some feedback pls

https://github.com/rikka0w0/MobZReborn/releases/tag/3.3.3_1.18.2
