### ISSUE TITLE
Crash report

### ISSUE THREAD

**Issue by Enterenn** [rikka0w0/MobZReborn#21]
I got a crash in game when I entered a Birch forest 
here's the report :

<details><summary>CRASH REPORT</summary>
---- Minecraft Crash Report ----
// I bet Cylons wouldn't have this problem.

Time: 5/16/22, 9:16 PM
Description: Exception ticking world

java.lang.NoClassDefFoundError: net/minecraft/class_3494$class_5123
	at net.mobz.entity.ToadEntity.method_5959(ToadEntity.java:100)
	at net.minecraft.class_1308.<init>(class_1308.java:144)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:43)
	at net.mobz.entity.ToadEntity.<init>(ToadEntity.java:84)
	at net.minecraft.class_1299.method_5883(class_1299.java:478)
	at net.minecraft.class_1948.method_8661(class_1948.java:519)
	at net.minecraft.class_3754.method_12107(class_3754.java:493)
	at net.minecraft.class_2806.method_17033(class_2806.java:171)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:338)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1395)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165)
Caused by: java.lang.ClassNotFoundException: net.minecraft.class_3494$class_5123
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:145)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 27 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.mobz.entity.ToadEntity.method_5959(ToadEntity.java:100)
	at net.minecraft.class_1308.<init>(class_1308.java:144)
	at net.minecraft.class_1314.<init>(class_1314.java:14)
	at net.minecraft.class_1296.<init>(class_1296.java:28)
	at net.minecraft.class_1429.<init>(class_1429.java:43)
	at net.mobz.entity.ToadEntity.<init>(ToadEntity.java:84)
	at net.minecraft.class_1299.method_5883(class_1299.java:478)
	at net.minecraft.class_1948.method_8661(class_1948.java:519)
	at net.minecraft.class_3754.method_12107(class_3754.java:493)
	at net.minecraft.class_2806.method_17033(class_2806.java:171)
	at net.minecraft.class_2806$class_3768.doWork(class_2806.java:338)
	at net.minecraft.class_2806.method_12154(class_2806.java:289)
	at net.minecraft.class_3898.method_17225(class_3898.java:649)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.class_3898.method_17224(class_3898.java:643)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1150)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:482)
	at net.minecraft.class_3900.method_17634(class_3900.java:62)
	at net.minecraft.class_3846.method_16907(class_3846.java:91)
	at net.minecraft.class_3846.method_16900(class_3846.java:146)
	at net.minecraft.class_3846.run(class_3846.java:102)

-- Affected level --
Details:
	All players: 1 total; [class_3222['Enterenn'/320, l='ServerLevel[New World]', x=-116.63, y=79.47, z=-252.39]]
	Chunk stats: 2927
	Level dimension: minecraft:overworld
	Level spawn location: World: (-112,65,-192), Section: (at 0,1,0 in -7,4,-12; chunk contains blocks -112,-64,-192 to -97,319,-177), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,-64,-512 to -1,319,-1)
	Level time: 705 game time, 705 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 128644 (now: false), thunder time: 167535 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.method_3813(MinecraftServer.java:910)
	at net.minecraft.server.MinecraftServer.method_3748(MinecraftServer.java:851)
	at net.minecraft.class_1132.method_3748(class_1132.java:97)
	at net.minecraft.server.MinecraftServer.method_29741(MinecraftServer.java:697)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:273)
	at java.base/java.lang.Thread.run(Thread.java:833)

-- System Details --
Details:
	Minecraft Version: 1.18.2
	Minecraft Version ID: 1.18.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.1, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 2687997208 bytes (2563 MiB) / 7038042112 bytes (6712 MiB) up to 8589934592 bytes (8192 MiB)
	CPUs: 12
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 3600 6-Core Processor              
	Identifier: AuthenticAMD Family 23 Model 113 Stepping 0
	Microarchitecture: unknown
	Frequency (GHz): 3.60
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: AMD Radeon RX 5700 XT
	Graphics card #0 vendor: Advanced Micro Devices, Inc. (0x1002)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x731f
	Graphics card #0 versionInfo: DriverVersion=30.0.15019.1005
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.40
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.40
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 30134.08
	Virtual memory used (MB): 20474.50
	Swap memory total (MB): 13824.00
	Swap memory used (MB): 412.85
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx8192m -Xms256m
	Fabric Mods: 
		additionaladditions: Additional Additions 4.0.0
		advancednetherite: Advanced Netherite 1.5.0-1.18.2
		adventurez: AdventureZ 1.4.10
		appleskin: AppleSkin 2.4.0+mc1.18.2
		aqupdgrizzly: Grizzly Bear mob 1.18-1.3
		architects_palette: Architect's Palette Fabric 1.7
		architectury: Architectury 4.4.60
		artifacts: Artifacts 7.0.3+fabric
		bclib: BCLib 1.4.5
		betteranimalsplus: Better Animals Plus 1.18.2-11.0.5
		betterdeserttemples: YUNG's Better Desert Temples 1.18.2-Fabric-1.0.0
		betterdungeons: YUNG's Better Dungeons 1.18.2-Fabric-2.1.0
		betterend: Better End 1.1.0
		betterf3: BetterF3 1.2.4
		bettermineshafts: YUNG's Better Mineshafts 1.18.2-Fabric-2.1.1
		betternether: Better Nether 6.1.1
		betterstrongholds: YUNG's Better Strongholds 1.18.2-Fabric-2.1.1
		biomemakeover: Biome Makeover 1.18.2-1.4.20
		blue_endless_jankson: jankson 1.2.1
		bosses_of_mass_destruction: Bosses of Mass Destruction (Beta) 1.3.7-1.18.2
		byg: Oh The Biomes You'll Go 1.4
		caffeineconfig: CaffeineConfig 1.1.0
		cardinal-components: Cardinal Components API 4.1.4
		cardinal-components-base: Cardinal Components API (base) 4.1.4
		cardinal-components-block: Cardinal Components API (blocks) 4.1.4
		cardinal-components-chunk: Cardinal Components API (chunks) 4.1.4
		cardinal-components-entity: Cardinal Components API (entities) 4.1.4
		cardinal-components-item: Cardinal Components API (items) 4.1.4
		cardinal-components-level: Cardinal Components API (world saves) 4.1.4
		cardinal-components-scoreboard: Cardinal Components API (scoreboard) 4.1.4
		cardinal-components-world: Cardinal Components API (worlds) 4.1.4
		charm: Charm 4.1.0
		charmonium: Charmonium 4.0.0
		chord: Chord 1.8.0+1.18.2-fabric
		cloth-basic-math: cloth-basic-math 0.6.1
		cloth-config: Cloth Config v6 6.2.62
		clumps: Clumps 8.0.0+8
		com_electronwill_night-config_core: core 3.6.4
		com_electronwill_night-config_toml: toml 3.6.4
		com_eliotlash_mclib_mclib: mclib 18
		com_eliotlash_molang_molang: molang 18
		com_github_llamalad7_mixinextras: MixinExtras 0.0.7
		com_moandjiezana_toml_toml4j: toml4j 0.7.2
		com_typesafe_config: config 1.4.1
		consistency_plus: Consistency Plus 0.5.0+1.18.2
		creeperoverhaul: Creeper Overhaul 1.3.1
		croptopia: Croptopia 2.0.0
		dawn: Dawn API 3.3.0
		decorative_blocks: Decorative Blocks 2.1.0
		dusk: Dragonfight Mod 1.18.2-2.2
		earthbounds: Earthbounds 1.18.2-1.1.1
		ecologics: Ecologics 1.5.4
		eldritch_mobs: Eldritch Mobs 1.11.0
		endgoblintraders: End Goblin Traders 1.5 (Re-upload)
		enhancedcelestials: Enhanced Celestials 2.0.7
		entityculling: EntityCulling-Fabric 1.5.1
		expandability: ExpandAbility 6.0.0
		fabric: Fabric API 0.51.1+1.18.2
		fabric-api-base: Fabric API Base 0.4.4+d7c144a860
		fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.0+2373a54560
		fabric-biome-api-v1: Fabric Biome API (v1) 8.0.4+7b0f312660
		fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.12+3ac43d9560
		fabric-command-api-v1: Fabric Command API (v1) 1.1.9+d7c144a860
		fabric-commands-v0: Fabric Commands (v0) 0.2.8+b4f4f6cd60
		fabric-containers-v0: Fabric Containers (v0) 0.1.21+d7c144a860
		fabric-content-registries-v0: Fabric Content Registries (v0) 3.0.3+d82b939260
		fabric-convention-tags-v1: Fabric Convention Tags 1.0.1+474e4f7960
		fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.1.11+3ac43d9560
		fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.17+2540745460
		fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.8+d7c144a860
		fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.19+d7c144a860
		fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.14+d7c144a860
		fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.13+d7c144a860
		fabric-item-api-v1: Fabric Item API (v1) 1.4.0+4457765560
		fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.11+91896a4960
		fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.12+54e5b2ec60
		fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.10+b4f4f6cd60
		fabric-language-kotlin: Fabric Language Kotlin 1.7.4+kotlin.1.6.21
		fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.0.3+2d83e92c60
		fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.0.11+d7c144a860
		fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.0+81ea5b3c60
		fabric-models-v0: Fabric Models (v0) 0.3.6+d7c144a860
		fabric-networking-api-v1: Fabric Networking API (v1) 1.0.21+d882b91560
		fabric-networking-v0: Fabric Networking (v0) 0.3.8+b4f4f6cd60
		fabric-object-builder-api-v1: Fabric Object Builder API (v1) 2.1.0+fe4ddef060
		fabric-particles-v1: Fabric Particles (v1) 0.2.12+526dc1ac60
		fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.8+0d9ab37260
		fabric-renderer-api-v1: Fabric Renderer API (v1) 0.4.13+d882b91560
		fabric-renderer-indigo: Fabric Renderer - Indigo 0.5.0+7faf0d8860
		fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.11+b4f4f6cd60
		fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.7+d7c144a860
		fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 2.0.2+54e5b2ec60
		fabric-rendering-v0: Fabric Rendering (v0) 1.1.13+b4f4f6cd60
		fabric-rendering-v1: Fabric Rendering (v1) 1.10.7+54e5b2ec60
		fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.3+91b7aa6660
		fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.4.18+2de5574560
		fabric-screen-api-v1: Fabric Screen API (v1) 1.0.10+d882b91560
		fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.0+1f6558e860
		fabric-textures-v0: Fabric Textures (v0) 1.0.12+3ac43d9560
		fabric-transfer-api-v1: Fabric Transfer API (v1) 1.6.0+2373a54560
		fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.0.0+bd8a4a1860
		fabricloader: Fabric Loader 0.14.5
		fabricshieldlib: Fabric Shield Lib 1.5.3-1.18
		feature_nbt_deadlock_be_gone: Feature NBT Deadlock Be Gone - Fabric 2.0.0+1.18.2-rc1
		ferritecore: FerriteCore 4.2.1
		fiber: fiber 0.23.0-2
		fishofthieves: Fish of Thieves 1.0.5
		forgeconfigapiport: Forge Config API Port 3.2.0
		friendsandfoes: Friends&Foes 1.3.4
		geckolib3: Geckolib 3.0.42
		geodes: More Geodes 1.4.2
		go-fish: Go Fish 1.5.0-1.18.2
		goblintraders: Goblin Traders 1.5.1
		immersive_armors: Immersive Armors 1.3.3
		immersive_weathering: Immersive Weathering 2.4.0
		incendium: Incendium + Seed Fix 5.0.3
		io_leangen_geantyref_geantyref: geantyref 1.3.11
		iris: Iris 1.2.4-build.38
		jankson: Jankson 4.0.0+j1.2.0
		java: OpenJDK 64-Bit Server VM 17
		libgui: LibGui 5.1.0+1.18
		libninepatch: LibNinePatch 1.1.0
		lithium: Lithium 0.7.9
		maelstrom_library: Maelstrom Library 1.2.4-1.18.2
		mavm: More Axolotl Variants Mod 1.0.7a
		minecraft: Minecraft 1.18.2
		mm: Manningham Mills 2.3
		mobz: MobZ 3.3.1
		modmenu: Mod Menu 3.2.2
		more-axolotls: More Axolotls 1.0.2
		morebannerfeatures: More Banner Features 1.1.3
		morevillagers-fabric: MoreVillagersFabric 3.2.0-SNAPSHOT
		multipart_entities: MultipartEntities 1.1.5-1.18.2
		npcvariety: NPC Variety 2.2.1
		omega-config: OmegaConfig 1.0.8
		org_anarres_jcpp: jcpp 1.4.14
		org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.6.21
		org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.6.21
		org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.1
		org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.1
		org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.2
		org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.2
		org_joml_joml: joml 1.10.2
		org_spongepowered_configurate-core: configurate-core 4.1.2
		org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		patchouli: Patchouli 1.18.2-67-FABRIC
		promenade: Promenade 2.6.1
		puzzleslib: Puzzles Lib 3.3.1
		reeses-sodium-options: Reese's Sodium Options 1.4.2
		repurposed_structures: Repurposed Structures 4.1.7+1.18.2
		revamped_phantoms: Revamped Phantoms 0.2.3
		roughlyenoughitems: Roughly Enough Items 8.1.457
		seedfix: Seed Fix 1.0.1
		sentimentality3: Sentimentality 3 1.5.0
		skylorlib: SkyLib 1.3.35
		sodium: Sodium 0.4.1+build.15
		sodium-extra: Sodium Extra 0.4.3
		starlight: Starlight 1.0.2+fabric.89b8d9f
		step-height-entity-attribute: Step Height Entity Attribute 1.0.0
		stonecutter_recipe_tags: Stonecutter Recipe Tags 3.0.1+1.18.bc850d5.fabric
		stoneholm: Stoneholm 1.4.3
		terrablender: TerraBlender 1.1.0.99
		terraform-shapes-api-v1: Terraform Shapes API (v1) 2.1.0
		thonkutil: ThonkUtil 2.14.1+1.18
		thonkutil-base: ThonkUtil Base 1.12.2+23c1dc2c60
		thonkutil-capes-v1: ThonkUtil Capes (v1) 1.3.2+9e23427060
		thonkutil-coords-v1: ThonkUtil Coords (v1) 1.0.19+9b80223760
		thonkutil-customization-v1: ThonkUtil Customization (v1) 1.0.14+9b80223760
		thonkutil-legacy: ThonkUtil Legacy 1.0.20+9b80223760
		thonkutil-modchecker-v1: ThonkUtil ModChecker (v1) 1.0.12+9b80223760
		thonkutil-potions-v0: ThonkUtil Potions (v0) 1.4.1+9b80223760
		thonkutil-titlescreen-v1: ThonkUtil TitleScreen (v1) 1.1.9+9b80223760
		thonkutil-trades-v1: ThonkUtil Trades (v1) 1.1.20+9b80223760
		tinyskeletons: Tiny Skeletons 3.2.1
		trinkets: Trinkets 3.3.1
		twigs: Twigs 1.1.3-patch1+1.18.2
		waystones: Waystones 2.5.1
		whisperwoods: Whisperwoods 1.18.2-2.1.0
		wilderworld: WilderWorld 2.1.2
		xaeroworldmap: Xaero's World Map 1.21.2
		yigd: You're in Grave Danger 1.3.5
		yungsapi: YUNG's API 1.18.2-Fabric-2.0.8
		yungsbridges: YUNG's Bridges 1.18.2-Fabric-2.1.0
		yungsextras: YUNG's Extras 1.18.2-Fabric-2.1.0
	Loaded Shaderpack: ComplementaryShaders_v4.4.zip
		Profile: HIGH (+0 options changed by user)
	Server Running: true
	Player Count: 1 / 8; [class_3222['Enterenn'/320, l='ServerLevel[New World]', x=-116.63, y=79.47, z=-252.39]]
	Data Packs: vanilla, Fabric Mods
	World Generation: Stable
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'

</details>

**Comment by rikka0w0** [comment]
Try this and give some feedback pls

https://github.com/rikka0w0/MobZReborn/releases/tag/3.3.3_1.18.2
