### ISSUE TITLE
Mod is outdated (Unable to make it work)

### ISSUE THREAD

**Issue by RoxerQC** [rikka0w0/MobZReborn#22]
Every time I try to make a new world, it crash the entire game. There is no workaround for it. I have a strong believe that is because of the cloth config API that is responsible for this as this one is using the UNUSED version of it. 

[crash-2022-05-21_03.13.35-client.txt](https://github.com/rikka0w0/MobZReborn/files/8747173/crash-2022-05-21_03.13.35-client.txt)

**Comment by rikka0w0** [comment]
Can you try this one and see if it resolves the issue?
https://github.com/rikka0w0/MobZReborn/releases/tag/3.3.4_1.18.2
