### ISSUE TITLE
Feature Request - 1.18.2 Forge

### ISSUE THREAD

**Issue by Tyrius1** [rikka0w0/MobZReborn#26]
Could you add a biome whitelist for each mob? 
Data tag would also work.

**Comment by rikka0w0** [comment]
I think a set of blacklists might be better? We can have a discussion on this.

**Comment by Tyrius1** [comment]
Blacklists would be easier when considering just vanilla but in the instance where you have 3 or 4 different mods adding new biomes a Whitelist becomes vastly more comfortable. 

You could auto generate biomes into the field as well and have people just remove the ones they don't want.

Ultimately I think Whitelist will be easier in the long run. Especially if you can auto fill existing biomes like Better Animals Plus does.

**Comment by rikka0w0** [comment]
Do you want to have a look at this mod:
https://www.curseforge.com/minecraft/mc-mods/in-control
