### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Rad233** [rikka0w0/MobZReborn#32]
I'm using:
Minecraft: 1.19.2 fabric
Fabric: 0.14.9
Mobz: 3.3.4 fabric
Fabric ShieldLib: 1.6.1 -1.19 fabric
Cloth config: 8.2.88 fabric
Fabric api: 0.72.0 +1.19.2

Crash-report:
[crash-2023-01-14_00.13.34-client.txt](https://github.com/rikka0w0/MobZReborn/files/10413365/crash-2023-01-14_00.13.34-client.txt)

**Comment by rikka0w0** [comment]
Version 3.3.4 does not support 1.19.2, use version 3.3.5:
https://github.com/rikka0w0/MobZReborn/releases/tag/3.3.5_1.19.2
