### ISSUE TITLE
Mixin causing crash due to possible interference with FabricShieldLib.

### ISSUE THREAD

**Issue by CringeStar** [rikka0w0/MobZReborn#35]
https://github.com/rikka0w0/MobZReborn/blob/3835fe46b28b39d48ffbceaa6bf364863b9f42e2/fabric/src/main/java/net/mobz/mixin/MetalShieldMixin.java#L11

This override I think is causing the issue [142](https://github.com/StellarWind22/Fabric-Shield-Lib/issues/142) in FabricShieldLib.

Here is the crash log provided on our issue: https://pastebin.com/JpakGKAx

You can head over to our issue for more detail.

**Comment by manu1978** [comment]
Works great with FabricShieldLib-1.6.0-1.19.jar version
https://www.curseforge.com/minecraft/mc-mods/fabric-shield-lib/files/3970058

**Comment by CringeStar** [comment]
That version of the library is outdated, as we are now on 1.7. Also, the other cause of this problem is that your mixin is declared abstract which causes the crash:

```
java.lang.AbstractMethodError: Method net/mobz/item/Shield.getCoolDownTicks()I is abstract
	at net.mobz.item.Shield.getCoolDownTicks(Shield.java)
	at com.github.crimsondawn45.fabricshieldlib.initializers.FabricShieldLibClient.lambda$onInitializeClient$0(FabricShieldLibClient.java:73)
	at net.fabricmc.fabric.api.client.item.v1.ItemTooltipCallback.lambda$static$0(ItemTooltipCallback.java:37)
	at net.minecraft.class_1799.handler$gao000$fabric-item-api-v1$getTooltip(net/fabricmc/fabric/mixin/item/client/ItemStackMixin.java 
```

**Comment by CringeStar** [comment]
Any updates on this?

**Comment by Chris-Creates** [comment]
also getting an error with this with shield lib.

**Comment by CringeStar** [comment]
Any updates?

**Comment by Sunconure11** [comment]
I'm having the same issue. It started happening after pulling C2ME.

https://gist.github.com/Sunconure11/b3162a9d7b1fdd9e365d33ffc07e3898

@rikka0w0 @stellarwind22

**Comment by CringeStar** [comment]
The main source of this issue appears to be the mixin in this mod is declared abstract. @rikka0w0

**Comment by Mathio95** [comment]
Having the same issue, any updates?

**Comment by Titodelux** [comment]
I am having the same issue u.u

**Comment by CringeStar** [comment]
> Manu's advice works fine for me.

It references an outdated version of the library, so it idnt a fix. Also, we are trying to update the library to our next version (1.7.1) and this bug has halted our development since we want to fix the issue in the update. @rikka0w0 Please update and fix your mod.

**Comment by rikka0w0** [comment]
In FabricShieldLib 1.7, one method has been renamed:
![image](https://github.com/rikka0w0/MobZReborn/assets/4704366/439c2174-30f5-4bc9-b63f-ab11537d3eeb)

I will update the 1.19.2 MobZ to support FabricShieldLib 1.7.

**Comment by CringeStar** [comment]
that seemed to fix the crash, so thanks!
