### ISSUE TITLE
Some shield's cooldown ticks are abstract

### ISSUE THREAD

**Issue by MeAsAlways** [rikka0w0/MobZReborn#37]
The game crashes at the "joining world phase" started happening after i updated all mods on Forge, even tough this mod wasnt updated. 
Fabric ver: 0.14.17/19 - neither works - it used to with .17

Crash log: java.lang.AbstractMethodError: Method net/mobz/item/Shield.getCoolDownTicks()I is abstract

**Comment by MeAsAlways** [comment]
Okay so since none of yall goofy asses responded i managed to solve it myself, I'll leave this here in case anyone needs it.
Solution is to install FabricShieldLib's 1.6.1-1.19 version instead of 1.7-1.19.2

Mc ver: 1.19.2, Fabric loader: 0.14.19 

Have a better day than I did!

**Comment by Sanriaa** [comment]
bro ong you saved me <3
