### ISSUE TITLE
Game crashes when summoning mob.

### ISSUE THREAD

**Issue by X-Machiavelli** [rikka0w0/MobZReborn#42]
When I use spawn egg to summon TOAD and GIANT TOAD, the game crashes immediately. Also, WASP is not summoned and cannot be observed. Since installing this mod, the game's logfile is over 1GB, even if I only play for a short time. My guess is that some specific mobs is the problem.

MC 1.21.1, NEO 21.1.71
Client side
mobz-4.3.0-neoforge

[crash-2024-10-17_19.11.34-client.txt](https://github.com/user-attachments/files/17410665/crash-2024-10-17_19.11.34-client.txt)
[latest.log](https://github.com/user-attachments/files/17410667/latest.log)

**Comment by rikka0w0** [comment]
These creature are work-in-progress, and I will fix them.

As you mentioned the game log was very big, can you find out the repeating error message and share with me?

**Comment by rikka0w0** [comment]
As #44 suggests, the Wasp caused the problem. You may have noticed that the error log contains something relevant to the vanilla Bee. This problem has been fixed for all MobZ versions run on Minecraft 1.20.5 to 1.21.3
