### ISSUE TITLE
Change modloader dependency to 0.12.12

### ISSUE THREAD

**Issue by itsdinkd** [rikka0w0/MobZReborn#7]
![image](https://user-images.githubusercontent.com/35115304/152593191-f508b8a5-772a-4f50-936a-5966109f8187.png)

As you see in the screenshot above, Modloader 0.13.0 is not available on curseforge. latest is 0.12.12. I use your 1.17.1 in my pack with the MC version overridden. I'd like to upgrade MobZ for everyone, I can do another manual override but at that point its just too much.

**Comment by yesn0t** [comment]
i have two questions : 
* what is the point of updating the strict dependencies so aggresively if the older versions work fine ? This mod absolutely doesn't requires fabric loader 0.13 , nor does it require fabric api 0.46.4 .
 these versions are only a couple days old, and most players and modpack makers haven't updated yet, and most importantly, **Fabric Loader 0.12.12 is still the recommended version** (indicated by the star icon)
![image](https://user-images.githubusercontent.com/96038595/152598635-b92aca35-bae3-4cee-8ba7-ad48701579e0.png)
* why are you @itsdinkd using a client other than the recommended client for fabric, then complaining about it ?
 fabric loader 0.13 has been available in multimc since release day.
 ![image](https://user-images.githubusercontent.com/96038595/152597145-3b1a2be9-9be3-46cf-9251-70bb8719e5e1.png)

**Comment by rikka0w0** [comment]
When I upgraded the mod, I looked at `https://fabricmc.net/versions.html`, it told me to use the 0.13.0 loader. I'm not aware of 0.12.12 until you guys tell me.

https://www.curseforge.com/minecraft/mc-mods/mobz/files/3637349

This release fixes the problem and relaxes loader version to 0.12.12

**Comment by itsdinkd** [comment]
> i have two questions :
> 
>     * what is the point of updating the strict dependencies so aggresively if the older versions work fine ? This mod absolutely doesn't requires fabric loader 0.13 , nor does it require fabric api 0.46.4 .
>       these versions are only a couple days old, and most players and modpack makers haven't updated yet, and most importantly, **Fabric Loader 0.12.12 is still the recommended version** (indicated by the star icon)
>       ![image](https://user-images.githubusercontent.com/96038595/152598635-b92aca35-bae3-4cee-8ba7-ad48701579e0.png)
> 
>     * why are you @itsdinkd using a client other than the recommended client for fabric, then complaining about it ?
>       fabric loader 0.13 has been available in multimc since release day.
>       ![image](https://user-images.githubusercontent.com/96038595/152597145-3b1a2be9-9be3-46cf-9251-70bb8719e5e1.png)

Because I make modpacks. Modpacks use Curseforge Launcher to export. Curseforge Launcher does not support 0.13.0 Therefore I cannot use MultiMC to build and export modpacks. 

Why are you commenting on issues that have nothing to do with you?

**Comment by itsdinkd** [comment]
> When I upgraded the mod, I looked at `https://fabricmc.net/versions.html`, it told me to use the 0.13.0 loader. I'm not aware of 0.12.12 until you guys tell me.
> 
> https://www.curseforge.com/minecraft/mc-mods/mobz/files/3637349
> 
> This release fixes the problem and relaxes loader version to 0.12.12

Thank you <3

**Comment by itsdinkd** [comment]
> i have two questions :
> 
>     * what is the point of updating the strict dependencies so aggresively if the older versions work fine ? This mod absolutely doesn't requires fabric loader 0.13 , nor does it require fabric api 0.46.4 .
>       these versions are only a couple days old, and most players and modpack makers haven't updated yet, and most importantly, **Fabric Loader 0.12.12 is still the recommended version** (indicated by the star icon)
>       ![image](https://user-images.githubusercontent.com/96038595/152598635-b92aca35-bae3-4cee-8ba7-ad48701579e0.png)
> 
>     * why are you @itsdinkd using a client other than the recommended client for fabric, then complaining about it ?
>       fabric loader 0.13 has been available in multimc since release day.
>       ![image](https://user-images.githubusercontent.com/96038595/152597145-3b1a2be9-9be3-46cf-9251-70bb8719e5e1.png)

Because I make modpacks. Modpacks require Curseforge Launcher to export. Curseforge Launcher does not support 0.13.0 Therefore I cannot use MultiMC to build and export modpacks.

My question to you is, why did you not read the full post? what is the purpose of you asking me that as my answer does not solve anything? If you read the full post, you would see that I was said, "I use your mod in my pack" that should already say enough about why I requested the dependency to be lowered. It's apparent you do not make modpacks. please do not add irrelevant comments to issues.

**Comment by yesn0t** [comment]
> Because I make modpacks. Modpacks require Curseforge Launcher to export. Curseforge Launcher does not support 0.13.0 **Therefore I cannot use MultiMC to build and export modpacks.**

read https://fabricmc.net/wiki/start before coming to your own wrong conclusions
![image](https://user-images.githubusercontent.com/96038595/152894225-f1b63e75-7e41-45bd-aab4-e569a8295f80.png)
